forms_and_logic/urls.py
from django.urls import path

from forms_and_logic.views import (
	account_view,
)

app_name = 'forms_and_logic'

urlpatterns = [
	path('<user_id>/', account_view, name="view"),
]

kalApp/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include # calling other urls.py in other folders 
from django.contrib.auth import views as auth_views # don't know, but it works for change password

from preference.views import(home_view, profile_view,savevalues,saveArticle) # real home page 
from forms_and_logic.views import (registration_view,
                                  reset_view,
                                  login_view,
                                  logout_view,
                                  password_change_success_view,
                                  account_search_view,
                                  account_view,
                                  ) 


urlpatterns = [

    #Rest API Framework urls, file urls.py in forms_and_logic api folder 
    path('api/', include('forms_and_logic.api.urls')),

    #path('', home_view, name = "home"),# real home page 
    path('', saveArticle, name = "home"),# work in progress  
    path('profile/',profile_view, name = "profile"),#place for users to edit there account like change password
    path('save/',savevalues, name = "save"), # to save user picked options 

    path('account/',account_view, name = "forms_and_logic"),#place for users to edit there account like change password

    path('register/', registration_view, name = "register-form"), # new users 
    path('reset/', reset_view, name = "reset-form"),  #change passwords 
    path('login/', login_view, name = "login-form"), #login goes to home 
    path('logout/', logout_view, name = "logout-form"), #logout goes to home   
    
    path('friend/',include ('friendship.url', namespace ='friend')), #this will be the page to see your friends
    path('news/', include('preference.urls')), #get ya news from preference folder
	path('search/', account_search_view,name="search"), # New url for account_search_view
    path('forms_and_logic/', include('forms_and_logic.urls', namespace='forms_and_logic')),

    path('admin/', admin.site.urls),# change password only works when having this 
    path('change-password/', auth_views.PasswordChangeView.as_view(template_name = "form_links/reset.html"), name = "change_password"), #django's defualt change password 
    path('password_change_success/', password_change_success_view, name = "password_change_done"), #redrict back to home.html

]

friendship/models.py
from django.db import models
from django.conf import settings
from django.utils import timezone
from django.dispatch.dispatcher import receiver #standard

import forms_and_logic #they couldn't find account from the next line so I added this so the code can find account
from forms_and_logic.models import Account #we need to find ourselves
from django.conf import settings #get the settings
from django.utils import timezone #get time

# Create your models here.

class FriendList(models.Model): #saving stuff
    user    =   models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='user')
                                     #you need to be real,  we need to be able to remove friends, they are named user
   # bio     =   models.textfield() #extra points hopefully

    friends =   models.ManyToManyField(settings.AUTH_USER_MODEL, related_name = 'friends', blank=True)
                                    #friend need to be real,  we need to be able to find friends, blank = true cause its possible to have no friends :(
    def __str__(self):
        return self().user.username

    def add_friend(self):
        if not forms_and_logic in self.friends.all(): #if they are not in our friendlist --searches forms_and_logic-friendlist for if they are already friend
            self.friends.add(forms_and_logic) #add to our account
            self.save #save the friends
    
    def remove_friend(self):
        if forms_and_logic in self.friends.all(): #if they are not in our friendlist --searches forms_and_logic-friendlist for if they are already friend
            self.friends.add(forms_and_logic) #add to our forms_and_logic
            self.save

    def unfriend(self,removee): #our friend unfriending us 
        remover_friends_list = self #the friendship destoryer --one doing unfriending
        remover_friends_list.remove_friend(removee)  # -its the action of unfriending by friendship destoryer on their side
        
        #we are deleting ourself from their friendlist
        friends_list = FriendList.objects.get(user=removee)
        friends_list.remove_friend(self.user)#we are gone from their friendlist

    def is_mutual_friend(self,friend): #are we even friends? both friends
        if friend in self.friends.all(): # checks if friend is in our friendlist
            return True #if they are its true
        return False #other wise its false T-T

class FriendRequest(models.Model): #the bits and bops that make a friend request happen labeling stuff
    #theres a couple steps in becoming friends #relationship
     #1 sender- person sending and starting the friendship request
     #2 receiver-person getting the friendship request
    sender = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete = models.CASCADE, related_name="sender")
    receiver = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete = models.CASCADE, related_name="receiver")

    is_active = models.BooleanField(blank=True, null=False, default=True)
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.sender.username

    def accept(self): #accept friend request of accepted so we add to our and their friendlist
        receiver_friend_list = FriendList.objects.get(user=self.receiver)
        if receiver_friend_list:
            receiver_friend_list.add_friend(self.sender) #receiver accepts so update their friendlist
            sender_friend_list= FriendList.objects.get(user=self.sender) #sender gets friend
            
            if sender_friend_list: #we are now friends so we update their friendlist
                sender_friend_list.add_friend(self.receiver)
                self.is_action = False
                self.save()
    
    def decline(self): #they/we rejected friendship
        self.is_active = False
        self.save()
    
    def cancel(self):#we decided to cancel the friend request we are making a notification
        self.is_active = False
        self.save()

friendship/views.py
from django.shortcuts import render #gives us the stack to actually send string around
from django.http import HttpResponse #send the link/payload
import json
from enum import Enum  #they all have to unique values
from forms_and_logic.models import Account#gives us the account models with info to use
from friendship.models import FriendRequest, FriendList #gives us 

def friends_list_view(request, *args, **kwargs):
	context = {}
	user = request.user
	if user.is_authenticated:
		user_id = kwargs.get("user_id")
		if user_id:
			try:
				this_user = Account.objects.get(pk=user_id)
				context['this_user'] = this_user
			except Account.DoesNotExist:
				return HttpResponse("That user does not exist.")
			try:
				friend_list = FriendList.objects.get(user=this_user)
			except FriendList.DoesNotExist:
				return HttpResponse(f"Could not find a friends list for {this_user.username}")
			
	return render(request, "friendship_links/friend_list.html", context)

def send_friend_request(request): # we are sending the friend request
	user = request.user #us user is the varaible to represent what we did
	payload = {} 
	if request.method == "POST" and user.is_authenticated: # get what they sent if we are logged in 
		user_id = request.POST.get("receiver_user_id") #what we get back is what our protental friend will use as a unique identifier
		if user_id: #if they are logged in we check... 
			receiver = Account.objects.get(pk=user_id) # we label them as athe receiver in our relation of 
			try:
				# Get any friend requests (active and not-active)
				friend_requests = FriendRequest.objects.filter(sender=user, receiver=receiver)
				# find if any of them are active (pending)
				
				try:
					for request in friend_requests:
						raise Exception("You already following them.")

					friend_request = FriendRequest(sender=user, receiver=receiver)
					friend_request.save()
					payload['response'] = "Following!."

				except Exception as e:
					payload['response'] = str(e)
					
			except FriendRequest.DoesNotExist: # there wasn't a already pending request
				# There are no friend requests so create one.
				friend_request = FriendRequest(sender=user, receiver=receiver)
				friend_request.save()
				payload['response'] = "Friend request sent."

			if payload['response'] == None: 
				payload['response'] = "Something went wrong."
		else:
			payload['response'] = "Unable to sent a friend request." #something went wrong... but we are not going to tell them
	else: #somehow they are able to see another proflie page and sees a friend button when they are not logged in
		payload['response'] = "You must be authenticated (logged in) to follow someone."
	return HttpResponse(json.dumps(payload), content_type="application/json")

def friend_requests(request, *args, **kwargs): #status of the follow
	return HttpResponse(json.dumps(payload), content_type="application/json")

def remove_friend(request, *args, **kwargs):
	user = request.user 
	payload = {}
	if request.method == "POST" and user.is_authenticated:
		user_id = request.POST.get("receiver_user_id")
		if user_id:
			try:
				removee = Account.objects.get(pk=user_id)
				friend_list = FriendList.objects.get(user=user)
				friend_list.unfriend(removee)
				payload['response'] = "Successfully removed that friend."
			except Exception as e:
				payload['response'] = f"Something went wrong: {str(e)}"
		else:
			payload['response'] = "There was an error. Unable to remove that follow."  #a mistake in case something went wrong specifically about the friend request being sent
	else:
		# should never happen 
		payload['response'] = "You must be authenticated to remove a follow." #how dare you remove your friend
	return HttpResponse(json.dumps(payload), content_type="application/json") #okay we are now updating the fact you've removed your friend from your friendlist

def get_friend_request_or_false(sender, receiver): #was there a friend request sent or not?? --> looks for if anyone sent a friend request 
    try:
        return FriendRequest.objects.get(sender=sender, receiver=receiver,is_active=True) #someone did send a friendrequest
    except FriendRequest.DoesNotExist: #no one sent a friend request
        return False

def cancel_friend_request(request, *args, **kwargs): #this doesn't work
	user = request.user
	payload = {}
	if request.method == "POST" and user.is_authenticated:
		user_id = request.POST.get("receiver_user_id")
		if user_id:
			receiver = Account.objects.get(pk=user_id)
			try:
				friend_requests = FriendRequest.objects.filter(sender=user, receiver=receiver, is_active=True)
			except FriendRequest.DoesNotExist:
				payload['response'] = "Nothing to cancel. Friend request does not exist."

			# There should only ever be ONE active friend request at any given time. Cancel them all just in case.
			if len(friend_requests) > 1:
				for request in friend_requests:
					request.cance()
				payload['response'] = "Friend request canceled."
			else:
				# found the request. Now cancel it
				friend_requests.first().cancel()
				payload['response'] = "Friend request canceled."
		else:
			payload['response'] = "Unable to cancel that friend request."
	else:
		# should never happen
		payload['response'] = "You must be authenticated to cancel a friend request."
	return HttpResponse(json.dumps(payload), content_type="application/json")

class FriendRequestStatus(Enum): #fixed and are the only cases that can happen
    NO_REQUEST_SENT = -1 # neither of the users sent a follow request
    THEM_SENT_TO_YOU = 0 # the act of seeing a friend request
    YOU_SENT_TO_THEM = 1 # the act of sending a friend request

friendship/templates/friendship_links/friend_list.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<style type="text/css">

	.friends-text{
		color: #000;
		font-weight: 500;
	}
	.friends-text-container{
		border: 1px solid #cccccc;
		border-radius: 12px;
	}
	.friends-btn:hover {
		background-color: #bfbfbf;
		border-color: #bfbfbf;
	}
	.dropdown-toggle::after { 
		content: none; 
	}
	.profile-link{
		color: #000;
	}

</style>

<div >
	<div>

		{% if friends %}
		<div>
		{% for friend in friends %}
		<div >
			
			<div >
				<a  href="{% url 'forms_and_logic:view' user_id=friend.0.pk %}">
					<h4 >{{friend.0.username}}</h4>: your followers
				</a>
			</div>
			
			<div >
				{% if friend.1 %}
					<div >
						<p>
							{{friend.1.username}}
							: Following 
						</p>

					</div>
				
				{% endif %}
			</div>
		</div>
		
		{% if forloop.counter|divisibleby:2 %}
		</div><div >
		{% endif %}
		
		{% endfor %}
		
		{% else %} <!-- If no friends -->
		<div >
			<p>No friends/follows :(</p>
		</div>
		{% endif %}
		</div>
	</div>
	
</div>

{% endblock content %}

friendship/templates/friendship_links/friend_requests.html
{% extends 'base.html' %}
{% load static %}

{% block content %}


<style type="text/css">
	.card{
		border-radius: 12px;
	}
	.dropdown-toggle::after { 
		content: none; 
	}
	.profile-link{
		color: #000;
	}
	.material-icons{
		font-size: 30px;
	}
	.material-icons:hover{
		cursor: pointer;
	}
	.confirm-friend-request{
		color: green;
	}
	.confirm-friend-request:hover {
		opacity: 0.3;
	}
	.decline-friend-request:hover {
		opacity: 0.3;
	}
	.decline-friend-request{
		color: red;
	}
</style>

<div class="container">
	<div class="card p-2">

		{% if friend_requests %}
		<div class="d-flex flex-row flex-wrap">
		{% for request in friend_requests %}
		<div class="card flex-row flex-grow-1 p-2 mx-2 my-2 align-items-center">
			<a class="profile-link" href="{% url 'account:view' user_id=request.sender.id %}">

			</a>
			<a class="profile-link" href="{% url 'account:view' user_id=request.sender.id %}">
				<div class="card-center px-2">
					<h4 class="card-title">{{request.sender.username}}</h4>
				</div>
			</a>
			<div class="">
	  			<span id="id_cancel_{{request.sender.id}}" class="decline-friend-request material-icons p-1" onclick='triggerDeclineFriendRequest("{{request.id}}")'>cancel</span>
	  			<span id="id_confirm_{{request.sender.id}}" class="confirm-friend-request material-icons p-1" onclick='triggerAcceptFriendRequest("{{request.id}}")'>check</span>
			</div>
		</div>
		{% if forloop.counter|divisibleby:2 %}
		</div><div class="d-flex flex-row flex-wrap">
		{% endif %}
		
		{% endfor %}
		
		{% else %} <!-- If no friends -->
		<div class="d-flex flex-row flex-grow-1 justify-content-center align-items-center p-4">
			<p>No results</p>
		</div>
		{% endif %}
		</div>
	</div>
	
</div>

<script type="text/javascript">

	function onFriendRequestAccepted(){
		location.reload();
	}

	function onFriendRequestDeclined(){
		location.reload();
	}

	function triggerAcceptFriendRequest(friend_request_id){
		acceptFriendRequest(friend_request_id, onFriendRequestAccepted)
	}

	function triggerDeclineFriendRequest(friend_request_id){
		declineFriendRequest(friend_request_id, onFriendRequestDeclined)
	}
</script>

{% include 'friendship_forms/accept_friend_request.html' %}
{% include 'friendship_forms/decline_friend_request.html' %}


{% endblock content %}

friendship/templates/friendship_links/send_friend_request.html
<script type="text/javascript"> 
//<!--JS code in a html file-->
	
	function sendFriendRequest(id, uiUpdateFunction){
		payload = { //unique info to use as the id
			"csrfmiddlewaretoken": "{{ csrf_token }}",
			"receiver_user_id": id, //we need a security feature when sending a jax on django
		}
		$.ajax({ //passing the payload
			type: 'POST',
			dataType: "json",
			url: "{% url 'friendship:friend-request' %}",
			timeout: 5000, 
			data: payload,
			success: function(data) {
				console.log("SUCCESS", data) //safely sent
				if(data['response'] == "Friend request sent."){
					// ui is updated
				}
				else if(data['response'] != null){ //it was not sent
					alert(data['response'])
				}
			}, 
			error: function(data) { //when everything goes wrong
				console.error("ERROR...", data)
				alert("Something went wrong."+data)
			},
			complete: function(data){
				uiUpdateFunction()
			}
		});
	}
	

</script>